apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-deployment
spec:
  selector:
    matchLabels:
      app: sidecar
  replicas: 1
  template:
    metadata:
      labels:
        app: sidecar
    spec:
      containers:
      - name: sidecar-interceptor
        image: sidecar-interceptor
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
      - name: sidecar-canary 
        image: sidecar-canary
        imagePullPolicy: Never
        ports:
        - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: sidecar-svc
  labels:
    app: sidecar
spec:
  type: LoadBalancer
  ports:
    - port: 4000
      targetPort: 4000
      name: http
  selector:
    app: sidecar
